### ISSUE TITLE
Is there a way to also support memrchr?

### ISSUE THREAD

**Issue by nicokoch** [BurntSushi/rust-memchr#1]
I was wondering if it would be possible for this library to also support memrchr?
I can see this might be difficult because memrchr is not a posix-defined functionality. 

And another (kinda related) question: Does this crate work on all platforms (especially windows)?

**Comment by BurntSushi** [comment]
> I was wondering if it would be possible for this library to also support memrchr?
I can see this might be difficult because memrchr is not a posix-defined functionality.

I would be OK adding it. IMO, we should provide an alternative when it's not available though.

> And another (kinda related) question: Does this crate work on all platforms (especially windows)?

Yes. This crate is used inside `regex` for some critical/common optimizations (which is tested on Windows).

**Comment by nicokoch** [comment]
Thanks for the reply! I will create a PR in the near future. 
> we should provide an alternative when it's not available though.

Would something using `Iterator::rposition()` suffice?

**Comment by BurntSushi** [comment]
> Would something using Iterator::rposition() suffice?

Absolutely. Either I or someone else can come along later and provide a more efficient implementation for systems that don't have `memrchr`. :-)

**Comment by bluss** [comment]
This can be closed.

**Comment by BurntSushi** [comment]
Thanks to @bluss! :)
