### ISSUE TITLE
Off by one index in Memchr iterator

### ISSUE THREAD

**Issue by matt2xu** [BurntSushi/rust-memchr#13]
It seems surprising to me that when using the Memchr iterator, the position that is returned when calling .next() is the position of the needle + 1. Looking at the tests of the crate, this is expected behavior. Could you please explain why it is this way? I could then make a PR with additional documentation and an example to show usage of the Memchr (and Memchr2/3) iterator.

**Comment by BurntSushi** [comment]
Uh... That seems surprising to me and sounds like a bug. cc @cholcombe973

**Comment by cholcombe973** [comment]
Yeah I seem to recall the problem was if I didn't return the needle position plus one it would get stuck in a infinite loop.

**Comment by BurntSushi** [comment]
*sigh* OK. Returning the index + 1 doesn't seem right to me at all. I really wish I caught that.

This has to be fixed. The question now is whether this requires a `2.0.0` release. It probably does.

**Comment by cholcombe973** [comment]
It seemed right at the time :-/. I think I was using it to split strings.

**Comment by matt2xu** [comment]
Any update on this? It would be nice to be zero-based IMO.

**Comment by BurntSushi** [comment]
Fixed in #18. Note that we decided it would be best to do a memchr 2 release for this change.
