### ISSUE TITLE
Feature request: memrnchr

### ISSUE THREAD

**Issue by glebm** [BurntSushi/rust-memchr#27]
It'd be nice to have a fast implementation that finds the first character that **isn't** the needle (like `find_last_not_of` in C++). This comes up in path parsing, e.g.:

https://github.com/danielpclark/faster_path/blob/master/src/path_parsing.rs#L21-L32

**Comment by BurntSushi** [comment]
Aren't paths really short? I'd be surprised if the overhead associated with memchr (and the like) didn't negate any win it might give you? It might be worth actually trying to write this implementation and benchmark it before adding it.

I'm also having a hard time understanding the linked code. It seems like `last_non_sep_i_before("/foo", 3)` would return `3`? The only interesting cases seem to be things like `/foo////`, right? In that case, why even bother with a vectorized routine anyway?

I also strongly suspect that the use of `unsafe` in that code is not necessary.

**Comment by glebm** [comment]
We do have extensive benchmarks, I've benchmarked four different implementations of that routine before choosing the current one ([benchmark](https://github.com/danielpclark/faster_path/pull/84/)).

```
running 3 tests
test tests::bench_extract_last_path_segment_bytes   ... bench:           8 ns/iter (+/- 0)
test tests::bench_extract_last_path_segment_pointer ... bench:           5 ns/iter (+/- 1)
test tests::bench_extract_last_path_segment_str     ... bench:          26 ns/iter (+/- 0)
```

> It might be worth actually trying to write this implementation and benchmark it in a real routine before adding it.

I believe a vectorized implementation will be be faster, because:

1. The library got a significant performance improvement, -20% time, for similar routines that were replaced with `memrchr` ([faster_path#132](https://github.com/danielpclark/faster_path/pull/132))

2. This method is called by an average Rails app over 100,000 times at startup. The average string length (an absolute path to a Ruby library) is larger than a cache line (100+ characters).

**Comment by glebm** [comment]
> I'm also having a hard time understanding the linked code. It seems like last_non_sep_i_before("/foo", 3) would return 3? The only interesting cases seem to be things like /foo////, right? In that case, why even bother with a vectorized routine anyway?

I've looked at all the call sites and you're right about this. It should be one or two iterations most of the time.

I'm convinced we don't need it to be vectorized or unsafe.

**Comment by BurntSushi** [comment]
All righty. FWIW, what I meant by "the unsafe is probably necessary" is that I suspect you could convince LLVM to omit bounds checks without unsafe, probably with an assertion (outside the loop). The guard on `>= 0` should take care of the lower end.

**Comment by glebm** [comment]
I did end up implementing a somewhat naive version of `memrnchr` here:
https://github.com/danielpclark/faster_path/blob/eeec238ea41c15f2ee4a7b703cc292110e5c524b/src/memrnchr.rs
