### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by HeroicKatora** [BurntSushi/rust-memchr#41]
> /// optimized routine that can be up to an order of magnitude master in some

should be

> /// optimized routine that can be up to an order of magnitude faster in some

https://github.com/BurntSushi/rust-memchr/blob/451d16d440928b5547b92317fd83fc4c937b7b91/src/lib.rs#L223

**Comment by BurntSushi** [comment]
This is fixed on master in https://github.com/BurntSushi/rust-memchr/pull/40.
