### ISSUE TITLE
Consider using `cfg-if` crate

### ISSUE THREAD

**Issue by VictorKoenders** [BurntSushi/rust-memchr#50]
Hello,

While reading through the code I noticed all the `#[cfg(...)]` statements, and I was wondering if you knew `cfg-if` existed? https://github.com/alexcrichton/cfg-if

This could help clean up the code and make sure that only 1 `fn` ever gets compiled in the code.

I'd be willing to implement this.

**Comment by BurntSushi** [comment]
I was using cfg-if. I ripped it out very recently. Look at the recent commits.

**Comment by VictorKoenders** [comment]
👍
