### ISSUE TITLE
approaching 1.0

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/rust-memchr#7]
This crate provides a small reasonably well defined API and probably won't ever see any breaking changes. While it may still need new additions or improved platform support, I expect it won't require backwards incompatible changes. Therefore, I propose cutting a 1.0 release in the next few weeks.

cc @bluss @nicokoch

**Comment by bluss** [comment]
Sounds good!

**Comment by nicokoch** [comment]
I like it!

**Comment by BurntSushi** [comment]
Done in https://github.com/BurntSushi/rust-memchr/commit/a191697c5bdb34ffbd7c85ffbc845e41c1a7f4fe
